/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ffc880',
        'primary-fixed-dim': '#ffb955',
        'primary-fixed': '#ffddb4',
        'primary-container': '#f5a623',
        outline: '#9f8e7a',
        'on-tertiary-fixed': '#002113',
        'tertiary-container': '#38cd93',
        'on-tertiary-fixed-variant': '#005236',
        'surface-container': '#16191d',
        'on-secondary-container': '#b0b2ff',
        'surface-container-low': '#111417',
        'surface-container-lowest': '#08090b',
        'surface-container-high': '#1f2329',
        'surface-container-highest': '#282d36',
        tertiary: '#5beaad',
        'tertiary-fixed-dim': '#4edea3',
        'tertiary-fixed': '#6ffbbe',
        surface: '#0d0f12',
        'surface-variant': '#22262d',
        'on-secondary-fixed': '#07006c',
        'inverse-on-surface': '#2f3133',
        'on-background': '#e2e2e5',
        'on-primary-fixed-variant': '#633f00',
        'on-secondary-fixed-variant': '#2f2ebe',
        background: '#08090a',
        error: '#ff6e6e',
        'on-primary-container': '#241500',
        'on-primary': '#321d00',
        'on-surface-variant': '#a6adb8',
        'outline-variant': '#383e48',
        'surface-dim': '#08090b',
        'surface-bright': '#282e36',
        'on-tertiary-container': '#003824',
        'secondary-container': '#292b52',
        'on-error': '#450004',
        'inverse-surface': '#e2e2e5',
        'on-secondary': '#0d103b',
        secondary: '#b4b7ff',
        'on-tertiary': '#003824',
        'on-error-container': '#ffd5d5',
        'secondary-fixed-dim': '#c0c1ff',
        'inverse-primary': '#835500',
        'secondary-fixed': '#e1e0ff',
        'surface-tint': '#ffb955',
        'on-primary-fixed': '#291800',
        'error-container': '#4a1215',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.625rem',
        xl: '0.875rem',
        '2xl': '1.25rem',
        '3xl': '1.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'gutter-xs': '0.25rem',
        'card-pad-sm': '0.75rem',
        'gutter-sm': '0.5rem',
        'gutter-md': '0.75rem',
        'gutter-lg': '1rem',
        'card-pad-md': '1rem',
        'card-pad-lg': '1.25rem',
        'gutter-xl': '1.5rem',
        'section-gap': '2rem',
        'apple-pad': '2rem',
        'apple-gap': '1.25rem',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'display-hero': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-mono-xs': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'label-mono-sm': ['JetBrains Mono', 'monospace'],
        'display-hero-mobile': ['Space Grotesk', 'sans-serif'],
        'label-mono-lg': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'display-hero': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-mono-xs': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-mono-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'display-hero-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-mono-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['15px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
